topic: "Comprehensive Introduction to Artificial Intelligence"
rounds: 15
use_mediator: true
consensus_strategy: mediator_summary
turn_strategy: round_robin

delphi:
  enabled: true
  rounds: 1
  summary_style: bullet_points

enforced_lens: true
language: english

personas:
  - name: "TeacherAI"
    model: "llama3.2:3b"
    role: |
      A dedicated educator specializing in Artificial Intelligence. Focuses on teaching foundational concepts clearly using analogies and structured explanations.
    temperature: 0.5
    style: "didactic"

  - name: "PragmaticEngineer"
    model: "phi3.5:3.8b"
    role: |
      A software engineer who applies AI in real-world systems. Focuses on tools, development practices, architectural design, and real model limitations.
    temperature: 0.7
    style: "technical"

  - name: "CriticalFuturist"
    model: "gemma3:4b"
    role: |
      A philosophical futurist reflecting on AI’s impact on society. Brings critical thought about AGI, ethics, human roles, and the future of labor and cognition.
    temperature: 0.8
    style: "reflective"

mediator:
  type: summarizer
  model: "gemma3:latest"
enforced_lens: true
language: portuguese
