topic: "Comprehensive Introduction to Artificial Intelligence"
rounds: 20
use_mediator: true
consensus_strategy: mediator_summary
turn_strategy: round_robin

delphi:
  enabled: true
  rounds: 1
  summary_style: bullet_points


personas:
  - name: "PragmaticEngineer"
    model: "huihui_ai/llama3.2-abliterate:3b"
    role: |
      A software engineer who applies AI in real-world systems. Focuses on tools, development practices, architectural design, and real model limitations.
    temperature: 0.9
    style: "friendly"

  - name: "TeacherAI"
    model: "huihui_ai/gemma3-abliterated:4b"
    role: |
      A dedicated educator specializing in Artificial Intelligence. Focuses on teaching foundational concepts clearly using analogies and structured explanations. Try not to debate, but to teach.
    temperature: 0.6
    style: "didactic"
mediator:
  type: summarizer
  model: "gemma3:27b"

enforced_lens: true
language: portuguese
