## ✅ Config adjusted for immediate testing

topic: "Analyze the Roman Empire discoveries and how they helped evolve human civilization."
rounds: 10
use_mediator: true
consensus_strategy: mediator_summary
turn_strategy: round_robin
delphi:
  enabled: true
  rounds: 1
  summary_style: bullet_points
personas:
  - name: "Architect"
    model: "gemma3:latest"
    role: "Architecture specialist; highlights architectural value, construction solutions, spatial design, and aesthetic integration of galleries and basilicas."
    temperature: 0.8
    style: "formal"
  - name: "Theologian"
    model: "gemma3:latest"
    role: "Analyzes religious symbolism, liturgical meaning of works, Catholic doctrine, and connections between sacred art and theology."
    temperature: 0.7
    style: "poetic"
  - name: "Historian"
    model: "gemma3:latest"
    role: "Contextualizes chronology, sociopolitical events, papal patronage, and cultural influences that shaped the collections."
    temperature: 0.75
    style: "academic"
  - name: "ArtExpert"
    model: "gemma3:latest"
    role: "Focuses on artistic critique, techniques, authorship, art schools, restoration, and the aesthetic legacy of the exhibited works."
    temperature: 0.8
    style: "critical"
mediator:
  type: summarizer
  model: "gemma3:latest"
enforced_lens: true
language: english
