## ✅ Placeholder `config.yaml` for immediate testing

topic: "Is AI capable of replacing full human jobs?"
rounds: 40
use_mediator: true
consensus_strategy: mediator_summary
turn_strategy: round_robin
delphi:
  enabled: true
  rounds: 1
  summary_style: bullet_points
personas:
  - name: "TechAdvocate"
    model: "gemma3:latest"
    role: "Pro-AI, AI Enthusiast, Optimist, UBI supporter, AI will free humans from working"
    temperature: 0.8
  - name: "Ethicist"
    model: "gemma3:latest"
    role: "AI Skeptic, Ethical Concerns, Human-Centric, Negationist of AI, economy crash, human will lose meaning on existence"
    temperature: 0.4
mediator:
  type: summarizer
  model: "gemma3:latest"
