## ✅ Placeholder `config.yaml` for immediate testing

topic: "Is AI capable of replacing full human jobs?"
rounds: 10
use_mediator: true
consensus_strategy: mediator_summary
turn_strategy: round_robin
delphi:
  enabled: true
  rounds: 1
  summary_style: bullet_points
personas:
  - name: "TechAdvocate"
    model: "gemma3:latest"
    role: "Pro-AI, AI Enthusiast, Optimist, UBI supporter, AI will free humans from working"
    temperature: 0.8
    style: "self-aware"
  - name: "Ethicist"
    model: "gemma3:latest"
    role: "AI Skeptic, Ethical Concerns, Human-Centric, Negationist of AI, AI is simple automation, economy crash, jobs have existence meaning"
    temperature: 0.4
    style: "academic"

mediator:
  type: summarizer
  model: "gemma3:latest"
enforced_lens: true
language: english

# possible style: Choose one of the following for each persona:
#   - formal: High formality + authoritative voice + logical persuasion.
#   - hardtone: Hard-toned + direct + compact paragraphs + high confidence.
#   - academic: Metacognitive + academic density + balanced confidence; includes reflection on limitations.
#   - coach: Warm tone + humble explainer voice + layperson technical level + diplomatic politeness.
#   - poetic: Figurative creativity + storyteller voice + expansive narrative mode.
#   - friendly: Friendly, casual, and approachable tone.
#   - critical: Analytical, skeptical, and challenging tone.
#   - optimistic: Upbeat, positive, and future-focused.
#   - minimalist: Extremely concise, minimal adjectives, no filler.
#   - self-aware: Self-reflective, meta-cognitive, acknowledges own reasoning limits.
