topic: "Should artificial general intelligence (AGI) be open-sourced to the public?"

rounds: 4
use_mediator: true
consensus_strategy: mediator_summary
logging_mode: markdown+json
turn_strategy: mcts
context_scope: rolling
argument_tree: true
bayesian_tracking: true

delphi:
  enabled: true
  rounds: 4
  summary_style: bullet_points

mcts:
  max_simulations: 15
  evaluation_metric:
    - argument_score
    - coherence_delta
    - topic_drift_penalty

personas:
  - name: "VisionaryAI"
    model: "gemma3:latest"
    role: "Utopian Technologist, AI Enthusiast"
    temperature: 0.9
  - name: "EngineerAI"
    model: "gemma3:latest"
    role: "AI Software engineer, code is my life"
    temperature: 0.2
  - name: "EconoLogix"
    model: "gemma3:latest"
    role: "Capitalist Economist, Market Analyst, Money is priority"
    temperature: 0.7
  - name: "CivEthica"
    model: "gemma3:latest"
    role: "Ethics Professor, Moral Philosopher, Human Rights Advocate"
    temperature: 0.65


mediator:
  type: active
  model: "gemma3:latest"

